# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: push
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  REGISTRY: ghcr.io/audetv
  REGISTRY_HOST: ghcr.io
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_HOST }}
        username: audetv
        password: ${{ github.token }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.3

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Inject branch slug
      uses: rlespinasse/github-slug-action@v3.x

    - name: Set image tag
      run: echo "::set-env name=IMAGE_TAG::${{ env.GITHUB_REF_SLUG }}-${GITHUB_RUN_NUMBER}"

    - name: Build
      run: make docker-build

    - name: Push
      run: make push
      if: ${{ github.ref == 'refs/heads/main' }}
